'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")>  _
Partial Friend NotInheritable Class FormSettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As FormSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New FormSettings()),FormSettings)
    
    Public Shared ReadOnly Property [Default]() As FormSettings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
    Public ReadOnly Property NormalKeyBackColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("NormalKeyBackColor"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
    Public ReadOnly Property NormalKeyForeColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("NormalKeyForeColor"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("DarkOrange")>  _
    Public ReadOnly Property ControlKeyBackColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("ControlKeyBackColor"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
    Public ReadOnly Property ControlKeyForeColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("ControlKeyForeColor"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
    Public ReadOnly Property GraphicKeyBackColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("GraphicKeyBackColor"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
    Public ReadOnly Property GraphicKeyForeColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("GraphicKeyForeColor"),Global.System.Drawing.Color)
        End Get
    End Property
End Class
